name: Top Languages

on:
  schedule:
    - cron: "0 0 * * *"   # Her gün güncelle
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub Metrics (Top Languages)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: hqkqn32
          template: classic
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: ""
          plugin_languages_limit: 8
          filename: top-langs.svg
